#!/usr/bin/python

#   Copyright (c) 2013-2015, Intel Performance Learning Solutions Ltd, Intel Corporation.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.


import os

virtenv = os.environ['OPENSHIFT_PYTHON_DIR'] + '/virtenv/'
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass
#
# IMPORTANT: Put any additional includes below this line.  If placed above this
# line, it's possible required libraries won't be in your searchable path
#

import so

from sdk.mcn import occi_ext


class MyBackend(occi_ext.Backend):

    def __init__(self):
        self.so = None
        
    def retrieve(self, entity, extras):
        # if init is the next action, no initialisation has begun
        if occi_ext.INIT_ACTION in entity.actions:
            entity.attributes['occi.mcn.stack.state'] = 'uninitialized'
            entity.attributes['occi.mcn.stack.id'] = ''
        # we deployed and possibly provisioned
        else:
            state, output, stack_id = self.so.so_e.state()
            entity.attributes['occi.mcn.stack.state'] = state
            entity.attributes['occi.mcn.stack.id'] = stack_id
            # to return SO specific attributes
            for kv in output:
                entity.attributes[kv['output_key']] = kv['output_value']

    def update(self, old, new, extras):
        pass
        # TODO: attributes would need to be defined by a mixin.
        # old.attributes.update(new.attributes)

    def delete(self, entity, extras):
        if occi_ext.INIT_ACTION not in entity.actions:
            self.so.so_e.dispose()
            entity.actions = []
        else:
            # Nothing to do...
            pass

    def init_me(self, entity, attributes, extras):
        # XXX: This method will disappear soon!
        token = extras['token']
        tenant = extras['tenant_name']
        self.so = so.ServiceOrchstrator(token, tenant)
        entity.actions = [occi_ext.DEPLOY_ACTION]

    def deploy_me(self, entity, attributes, extras):
        self.so.so_e.deploy()
        # only available action is now provision
        entity.actions = [occi_ext.PROVISION_ACTION]

    def provision_me(self, entity, attributes, extras):
        self.so.provision()
        # no more actions available in this state
        entity.actions = []

application = occi_ext.Application(MyBackend())

#
# Below for testing only
#
if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    # Wait for a single request, serve it and quit.
    httpd.serve_forever()