#!/bin/bash

echo "Downloading MCN SDK"

wget --no-check-certificate "https://owncloud.mobile-cloud-networking.eu/owncloud/public.php?service=files&t=0b30b6031281849d1eaffd27ce92cf08&download" -O $OPENSHIFT_DATA_DIR/sdk.zip 
pip install $OPENSHIFT_DATA_DIR/sdk.zip

